name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  Destroy_terraform_Template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform initialize
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve -lock=false
